### ISSUE TITLE
`pip` should not be included in requirements.txt

### ISSUE THREAD

**Issue by sjvrijn** [vinkenoogm/SVM-hb-NL#17]
1. `pip` is not needed for the code itself
2. installing `pip` needs `python -m pip install ...` instead of just `pip install ...`, so having it included in `requirements.txt` would interrupt the installation process:
```
$ pip install -r requirements.txt
[ ... output omitted for brevity ... ]
ERROR: To modify pip, please run the following command:
python -m pip install -r requirements.txt
```

**Comment by vinkenoogm** [comment]
Removed pip from requirements.txt
