### ISSUE TITLE
Add installation instructions in README

### ISSUE THREAD

**Issue by sjvrijn** [vinkenoogm/SVM-hb-NL#6]
It would be more explicit (and nice) to provide the exact setup commands in the Requirements section of the README. E.g:

> Clone this repository:
> ```bash
> git clone git@github.com:vinkenoogm/SVM-hb-NL.git
> cd SVM-hb-NL
> ```
> Create and activate a virtual environment, e.g. using `python -m venv venv`, then install the required packages:
> ```bash
> pip install -r requirements.txt
> ```

**Comment by vinkenoogm** [comment]
added this info to the readme
